Reduce log messages for APIKey changes when no API key is configured
dotnet/dotnet-monitor pull request #1510
Opened 2022-02-16 21:06 UTC by kelltrick

Removes unnecessary api config warning messages when no Api key is configured.
- Adds a bool to the internal `MonitorApiKeyConfiguration` object that tracks if any value was provided for the 2 settings. If null was passed, the log messages are omitted.
Resolves #1509

2022-02-16 21:32 UTC, wiktork approved these changes

2022-02-16 21:59 UTC, jander-msft commented
Doesn't this mean that if the ApiKey is not configured, then there won't be anything in the logs about the missing configuration? The logs will only show that all requests were challenged, correct?

2022-02-16 22:22 UTC, kelltrick commented
> Doesn't this mean that if the ApiKey is not configured, then there won't be anything in the logs about the missing configuration? The logs will only show that all requests were challenged, correct?

I'm not sure what you're asking. These are the cases I tested:
1. API Configuration is present, either `Authentication:MonitorApiKey:Subject` or `Authentication:MonitorApiKey:PublicKey` are not null.
  - The passed config is valid and correct, then you get this output:
```
12:58:09 info: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[25]
      MonitorApiKey settings have changed. The new settings have passed validation.
```
  - The passed config is invalid for any reason; you get one or more validation errors like this:
```
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The Subject field is required.
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The PublicKey field is required.
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The configuration parameter PublicKey must be base64Url encoded, the value '' could not be parsed as a base64Url-encoded string.
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The configuration parameter PublicKey must be contain a valid jwk, the value "" could not be parsed as a Json Web Key. The expected format is a Json Web Key written as JSON which is base64Url encoded. [Exception Message].
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
    MonitorApiKey settings are invalid: The configuration field PublicKey contains private key information. The private key information is not required for dotnet-monitor to verify a token signature and it is strongly recomended to only provide the public key.
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[26]
    The configuration field PublicKey contains private key information. The private key information is not required for dotnet-monitor to verify a token signature and it is strongly recomended to only provide the public key.
```
2. API Configuration is not present, **both** `Authentication:MonitorApiKey:Subject` and `Authentication:MonitorApiKey:PublicKey` are null. No output will be given with this change. Previously you would see:
```
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The Subject field is required.
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The PublicKey field is required.
12:58:25 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The configuration parameter PublicKey must be base64Url encoded, the value '' could not be parsed as a base64Url-encoded string.
```

If this is truly an optional parameter (which we define it as) we should allow things like Windows auth to be used.

This PR does not change any of the functional auth configuration, the `RejectAllSecurityValidator` SecurityTokenValidator will still be attached if the configuration is not present (case `2` from above); which causes all Authorization Headers of type `Bearer` to fail.

2022-02-16 22:30 UTC, jander-msft commented
> 2. API Configuration is not present, **both** `Authentication:MonitorApiKey:Subject` and `Authentication:MonitorApiKey:PublicKey` are null. No output will be given with this change.

This is what I was talking about. It will be very non-obvious when someone runs the dotnet-monitor image, tries to access a route, and gets a HTTP 401 no matter what they do and there is no logging as to why there's always a HTTP 401. I think we're going to get a lot of people logging issues here along the lines of "why can't I access any routes when running in the container but I run it locally everything works just fine?"

> If this is truly an optional parameter (which we define it as)

Where do we define that it is optional? You've removed the logging when none of it is configured. So prior to this change, we were telling users that it is needed and now you are making it optional. This is definitely not optional on Linux, where Windows auth is not available.

2022-02-16 22:31 UTC, jander-msft commented
> I'd like to decrease the amount of information a user gets blasted with whenever they start `dotnet-monitor`.

Decreasing, sure. Completely removing when completely unconfigured, I'm not convinced.

2022-02-16 22:34 UTC, jander-msft requested changes
At least log something (especially on Linux when there is no automatically configured auth option) so that users can understand why all requests are 401'd, even if it is a single log statement that tells them to go configure it and maybe a fwlink to docs.

2022-02-16 22:37 UTC, kelltrick commented
> > 2. API Configuration is not present, **both** `Authentication:MonitorApiKey:Subject` and `Authentication:MonitorApiKey:PublicKey` are null. No output will be given with this change.
> 
> This is what I was talking about. It will be very non-obvious when someone runs the dotnet-monitor image, tries to access a route, and gets a HTTP 401 no matter what they do and there is no logging as to why there's always a HTTP 401. I think we're going to get a lot of people logging issues here along the lines of "why can't I access any routes when running in the container but I run it locally everything works just fine?"
> 
> > If this is truly an optional parameter (which we define it as)
> 
> Where do we define that it is optional? You've removed the logging when none of it is configured. So prior to this change, we were telling users that it is needed and now you are making it optional. This is definitely not optional on Linux, where Windows auth is not available.

It's optional because the `Authentication` config parameter is optional: https://github.com/dotnet/dotnet-monitor/blob/4cca8d9f0d8f4f0b06328e508d0d7954afd6cdfb/documentation/schema.json#L19-L29

2022-02-16 22:43 UTC, jander-msft commented
> > > 2. API Configuration is not present, **both** `Authentication:MonitorApiKey:Subject` and `Authentication:MonitorApiKey:PublicKey` are null. No output will be given with this change.
> > 
> > 
> > This is what I was talking about. It will be very non-obvious when someone runs the dotnet-monitor image, tries to access a route, and gets a HTTP 401 no matter what they do and there is no logging as to why there's always a HTTP 401. I think we're going to get a lot of people logging issues here along the lines of "why can't I access any routes when running in the container but I run it locally everything works just fine?"
> > > If this is truly an optional parameter (which we define it as)
> > 
> > 
> > Where do we define that it is optional? You've removed the logging when none of it is configured. So prior to this change, we were telling users that it is needed and now you are making it optional. This is definitely not optional on Linux, where Windows auth is not available.
> 
> It's optional because the `Authentication` config parameter is optional:
> 
> https://github.com/dotnet/dotnet-monitor/blob/4cca8d9f0d8f4f0b06328e508d0d7954afd6cdfb/documentation/schema.json#L19-L29

The JSON schema is a guide to what's allowable, not the definitive source of correctness. Just because the schema allows it doesn't mean that the tool will run without issue.

Further, the fact that it is optional in the schema is a technical detail of the fact that it was generated from a property whose type is an object, which are nullable. It is also not required that the Authentication section is set in the settings.json file; it can be set via environment variable or key-per-file configuration. Thus, it should be optional in the schema.

2022-02-16 22:48 UTC, kelltrick commented
Ahh, I see what you mean. The user still gets a log when they make a request (it's just delayed until the request is actually made). This didn't change:

```
14:45:57 info: Microsoft.Diagnostics.Tools.Monitor.LiveJwtBearerHandler[1]
      => SpanId:74ecbb66ba88723a, TraceId:da5094185bcc3f9370d2097f065371bd, ParentId:0000000000000000 => ConnectionId:0HMFHJOBFU4KO => RequestPath:/info RequestId:0HMFHJOBFU4KO:00000002
      Failed to validate the token.
      System.InvalidOperationException: API key authentication not configured.
         at Microsoft.Diagnostics.Tools.Monitor.RejectAllSecurityValidator.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in D:\repos\github\dotnet-monitor\src\Tools\dotnet-monitor\Auth\RejectAllSecurityValidator.cs:line 30
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()```

2022-02-16 23:10 UTC, kelltrick commented
How about this, 1 new single error message (with a link to the docs):
```
15:09:37 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[56]
      API key authentication not configured. See https://aka.ms/dotnet-monitor-apikeydoc
```

2022-02-16 23:21 UTC, jander-msft commented
> How about this, 1 new single error message (with a link to the docs):
> 
> ```
> 15:09:37 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[56]
>       API key authentication not configured. See https://aka.ms/dotnet-monitor-apikeydoc
> ```

It should technically be an fwlink since it goes to a resource that is potentially localizable.

I'm going to see if we can make an effort to get official documentation up on https://docs.microsoft.com/en-us/dotnet/core/diagnostics/

2022-02-17 18:57 UTC, kelltrick commented
Having this as an FWLink seems reasonable @jander-msft can you check the way I did the Culture capture in the LoggingExtensions.cs? 

https://github.com/dotnet/dotnet-monitor/blob/bfb0e81d7cbc0891410b0f5b3e7effae522cc336/src/Tools/dotnet-monitor/Strings.resx#L383-L389
https://github.com/dotnet/dotnet-monitor/blob/bfb0e81d7cbc0891410b0f5b3e7effae522cc336/src/Tools/dotnet-monitor/LoggingExtensions.cs#L305-L309
https://github.com/dotnet/dotnet-monitor/blob/bfb0e81d7cbc0891410b0f5b3e7effae522cc336/src/Tools/dotnet-monitor/LoggingExtensions.cs#L555-L558

2022-02-17 19:59 UTC, kelltrick commented on src/Tools/dotnet-monitor/Strings.resx
> +    <value>API key authentication not configured. See https://go.microsoft.com/fwlink/?linkid=2187444&amp;clcid=0x{0:X3}</value>
yep, I looked through more of the links and the formatter appears to be "x"

2022-02-17 20:06 UTC, jander-msft approved these changes

2022-02-17 20:55 UTC, merged

2022-04-07 20:52 UTC, jander-msft commented
/backport to release/6.x